<?php

namespace MyPortal\HRS_Api\Service\Mapping;

/**
 * Class ServiceFacilities
 *
 * @package MyPortal\HRS_Api\Service\Mapping
 */
class ServiceFacilities extends AbstractMapping
{
    protected $data = [
        1 => 'Dusche/WC',
        2 => 'Badewanne',
        4 => 'Bettwäsche',
        5 => 'Handtücher',
        6 => 'Reise-/Kinderbett',
        7 => 'TV',
        9 => 'Kabel/Sat',
        10 => 'Radio',
        11 => 'Telefon',
        13 => 'Balkon',
        14 => 'Terrasse',
        17 => 'rollstuhlgerecht',
        18 => 'Tiere willkommen',
        19 => 'behindertenfreundlich(Kat.)',
        20 => 'Nichtraucher',
        21 => 'Seeblick',
        22 => 'Mini-Bar',
        23 => 'Insektenschutz/Gaze',
        24 => 'Waschmaschine',
        25 => 'Dusche',
        26 => 'Spülmaschine',
        27 => 'Trockner',
        28 => 'Schreibtisch',
        29 => 'Haartrockner',
        30 => 'Kachelofen',
        31 => 'Klimaanlage',
        32 => 'allergikerger. (tierfrei)',
        33 => 'Mikrowelle',
        34 => 'Kühlschrank',
        35 => 'separate Küche',
        36 => 'Küche (Pantry/Mini)',
        37 => 'Gäste-WC',
        38 => 'Meerblick',
        39 => 'CD-Player',
        40 => 'rollstuhlgeeignet',
        41 => 'Backofen',
        42 => 'Kamin',
        43 => 'Heizung',
        44 => 'WC-Toilette',
        45 => 'DVD-Player',
        46 => 'Internet - WLAN',
        47 => 'Internet - LAN',
        48 => 'TC-Trockentoilette',
        49 => 'Teppichboden',
        50 => 'Hochstuhl',
        51 => 'Raucher',
        52 => 'Strom 230 Volt',
        53 => 'Schiff/Koje',
        54 => 'Schiff/Kombüse',
        55 => 'Schiff/Salon',
        56 => 'Sauna (Kat.)',
        57 => 'Safe',
        58 => 'fließend Wasser',
        59 => 'Schwimmbecken',
        60 => 'Pool\ (Kat.)',
        61 => 'Pool beheizt (Kat.)',
        62 => 'seperates Grundstück',
        63 => 'Gefriermöglichkeit',
        64 => 'behindertengerecht',
        65 => 'TV - Flachbild',
        66 => 'getrennt stehende Betten',
        67 => 'Infrarot-Kabine',
        68 => 'Bergblick',
        69 => 'Panoramablick',
        70 => 'Küche (offen)',
        71 => 'Tiere nicht erlaubt',
        72 => 'Wecker',
        73 => 'Brötchenservice',
        74 => 'Frühstücksservice',
        75 => 'Einkaufsservice',
        76 => 'Wohn/Schlafraum komb',
        77 => 'geeignet für Gäste mit Sinneseinschränkungen',
        78 => 'zusätzliches Bad',
        79 => 'Whirlpool',
        80 => 'Strandkorb (persönlich)',
        81 => 'Kamin Ethanol/Gas',
        82 => 'Gemeinschaftsküche',
        83 => 'Etagenbett',
        84 => 'Doppelbett',
        85 => 'französisches Bett',
        86 => 'Schlafsofa',
        87 => 'Schrankbett',
        88 => 'Bad/WC',
        89 => 'ebenerdig',
        90 => 'Ruderboot inklusive',
        91 => 'Wasseranschl.',
        92 => 'Strom',
        93 => 'Abwasser 100 mm',
        94 => 'Abwasser 50 mm',
        95 => 'Einzelbett',
        96 => 'Etagen WC',
        97 => 'Etagen-Dusche',
        98 => 'Spielekonsole',
        99 => 'Deichblick',
        173 => 'Smart-TV',
        177 => 'Sky-TV',
        1000 => 'Tiere auf Anfrage',
        1001 => 'Herd',
        1002 => 'Rauchmelder',
        1003 => 'Bügeleisen',
        1004 => 'Toaster',
        1005 => 'Dunstabzug',
        1006 => 'Staubsauger',
        1007 => 'Bidet',
        1008 => 'Abstellraum',
        1009 => 'Getrennte Schlafzimmer',
        1010 => 'Wohnzimmer',
        1011 => 'Wohnzimmer',
        1012 => 'Dachzimmer / -wohnung',
        1013 => 'Schlafzimmer',
        1014 => 'mehrere Schlafzimmer',
        1015 => 'Separater Wohnraum',
        1016 => 'Parterre',
    ];
}
